[package]
name = "numgen"
version = "0.1.0"
authors = ["aswasa"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.2"
ferris-says = "0.2.0"
ferris_print = "0.1.0"
[[bin]]
name = "numgen"
path = "main.rs"
